Repository WildCodeSchool/orleans-202103-php-project-jobpermut, pull requests merged in 2021-06, with the labels that each got.

#3 close #2
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
Labels: Reviewed

#13 add logo and css
  assets/images/logo_navbar.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#15 S01 us02 01 footer structure
  templates/includes/_footer.html.twig
  templates/layout.html.twig
Labels: Corrections done, Reviewed

#19 dev to master
  assets/app.js
  assets/fonts/Croogla4F.ttf
  assets/images/logo_navbar.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#14 S01 us03 banner
  assets/images/logo_chrono.svg
  assets/images/logo_header.png
  assets/images/logo_home.svg
  assets/images/logo_map.svg
  assets/styles/header.scss
  templates/home/index.html.twig
  templates/includes/_header.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#27 US01-04 color css
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#29 FIX header and styles
  assets/styles/app.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/includes/_header.html.twig
  webpack.config.js
Labels: Reviewed

#37 entity
  config/packages/security.yaml
  migrations/Version20210607093228.php
  src/Entity/User.php
  src/Repository/UserRepository.php
Labels: Reviewed

#39 S01 us02 02 footer css
  assets/images/contact.png
  assets/images/logo_navbar.png
  assets/styles/footer.scss
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed

#42 fix_webpack
  webpack.config.js
Labels: Reviewed

#46 s02_us14_fixtures_users
  composer.json
  composer.lock
  src/DataFixtures/UserFixtures.php
  symfony.lock
Labels: Reviewed

#47 FIX: footer contact img
  templates/includes/_footer.html.twig
Labels: Reviewed

#40 Us06 témoignages
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Conflicts resolved, Reviewed

#44 Us4 01 importer openstreetmap
  assets/freeMap.js
  assets/styles/home.scss
  config/packages/webpack_encore.yaml
  package.json
  templates/home/index.html.twig
  templates/layout.html.twig
  webpack.config.js
  yarn.lock
Labels: Corrections done, Reviewed

#51 Changement favicon
  assets/images/favicon.png
Labels: Reviewed

#53 fix anchor link on decouvrir jobpermut button
  templates/home/index.html.twig
  templates/includes/_presentation.html.twig
Labels: Reviewed

#56 FIX: presentation styles file
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/includes/_presentation.html.twig
Labels: Reviewed, Waiting For Lucy

#52 S02 us14 login
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/Security/AppAuthenticator.php
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
  templates/security/login.html.twig
Labels: Reviewed, Waiting For Lucy

#57 dev to master before rdv client please
  assets/freeMap.js
  assets/images/contact.png
  assets/images/favicon.png
  assets/images/logo_chrono.svg
  assets/images/logo_final.png
  assets/images/logo_header.png
  assets/images/logo_home.svg
  assets/images/logo_map.svg
  assets/images/logo_navbar.png
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/packages/webpack_encore.yaml
  migrations/Version20210607093228.php
  package.json
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/AppAuthenticator.php
  symfony.lock
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
  templates/layout.html.twig
  templates/security/login.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, Waiting For Lucy

#59 Fix_Responsive
  assets/styles/home.scss
Labels: Reviewed

#61 S02 us14 login redirection
  src/Controller/SecurityController.php
  src/Security/AppAuthenticator.php
  templates/includes/_login.html.twig
Labels: Reviewed

#60 dev to master demo
  assets/styles/home.scss
  src/Controller/SecurityController.php
  src/Security/AppAuthenticator.php
  templates/includes/_login.html.twig
Labels: Reviewed

#63 Fix responsive témoignage
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#64 Ajout effet rotation
  assets/images/logo_permut.png
  assets/styles/navbar.scss
  templates/includes/_navbar.html.twig
Labels: Reviewed

#62 Us17 01 profil
  assets/styles/profile.scss
  migrations/Version20210610084847.php
  migrations/Version20210610091034.php
  migrations/Version20210610140303.php
  migrations/Version20210610151209.php
  migrations/Version20210610153200.php
  migrations/Version20210610183021.php
  src/Controller/ProfileController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/SubscriptionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/RegisteredUser.php
  src/Entity/Subscription.php
  src/Entity/User.php
  src/Repository/RegisteredUserRepository.php
  src/Repository/SubscriptionRepository.php
  templates/profile/show.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#69 FIX: header home and responsive nav
  assets/images/check.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#68 fix animation logo navbar
  assets/styles/navbar.scss
  templates/includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#79 add dropdown
  assets/styles/navbar.scss
  templates/includes/_navbar.html.twig
Labels: Reviewed

#73 S03 us14 modal
  assets/app.js
  assets/login.js
  assets/styles/app.scss
  assets/styles/navbar.scss
  config/packages/security.yaml
  phpmd.xml
  phpstan.neon
  src/Controller/SecurityController.php
  src/Security/AppAuthenticator.php
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
Labels: Conflicts resolved, Reviewed

#82 dev -> master
  assets/app.js
  assets/images/check.jpg
  assets/images/logo_permut.png
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/profile.scss
  config/packages/security.yaml
  migrations/Version20210610084847.php
  migrations/Version20210610091034.php
  migrations/Version20210610140303.php
  migrations/Version20210610151209.php
  migrations/Version20210610153200.php
  migrations/Version20210610183021.php
  phpmd.xml
  phpstan.neon
  src/Controller/ProfileController.php
  src/Controller/SecurityController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/SubscriptionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/RegisteredUser.php
  src/Entity/Subscription.php
  src/Entity/User.php
  src/Repository/RegisteredUserRepository.php
  src/Repository/SubscriptionRepository.php
  src/Security/AppAuthenticator.php
  templates/home/index.html.twig
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
  templates/profile/show.html.twig
  webpack.config.js
Labels: Reviewed

#83 fix master 01
  src/Entity/User.php
  templates/includes/_navbar.html.twig
Labels: Reviewed

#86 dev -> master fix and other pr if ok
  src/Entity/User.php
  templates/includes/_navbar.html.twig
Labels: Reviewed

#87 Fix_presentation
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#90 Fix modal
  templates/includes/_footer.html.twig
  templates/includes/_login.html.twig
Labels: Reviewed

#85 S03 us20 super admin home page
  assets/styles/admin.scss
  config/packages/security.yaml
  src/Controller/AdminController.php
  src/DataFixtures/UserFixtures.php
  templates/admin/index.html.twig
  templates/includes/_navbar.html.twig
  webpack.config.js
Labels: Corrections done, Question, Reponse, Waiting For Lucy

#84 Us17 02 edit profile
  assets/styles/profile.scss
  assets/styles/variables.scss
  composer.json
  migrations/Version20210616135313.php
  migrations/Version20210616140031.php
  migrations/Version20210616140959.php
  migrations/Version20210616141224.php
  migrations/Version20210617131628.php
  src/Controller/ErrorController.php
  src/Controller/ProfileController.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/RegisteredUser.php
  src/Entity/Subscription.php
  src/Entity/User.php
  src/Form/RegisteredUserType.php
  templates/includes/_navbar.html.twig
  templates/profile/_form.html.twig
  templates/profile/edit.html.twig
  templates/profile/show.html.twig
Labels: Conflicts resolved, Reviewed

#95 FIX: fixtures username
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#98 FIX: navbar
  assets/styles/navbar.scss
  templates/includes/_navbar.html.twig
Labels: Reviewed

#97 S03 us21 api rome
  .env
  config/services.yaml
  migrations/Version20210621145108.php
  src/Controller/HomeController.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/Entity/RegisteredUser.php
  src/Form/RegisteredUserType.php
  src/Service/ApiRome/ApiRome.php
  src/Service/ApiRome/ApiRomeAppellations.php
  src/Service/ApiRome/ApiRomeConfig.php
  src/Service/ApiRome/ApiRomeJobs.php
  src/Service/ApiRome/ApiRomeOgr.php
  src/Service/ApiRome/ApiRomeToken.php
  templates/profile/_form.html.twig
Labels: Question

#100 FIX: js animation HOME
  assets/app.js
  package.json
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#108 fix_logout_ok
  src/Controller/SecurityController.php
Labels: Reviewed

#96 S03 us13 inscription
  assets/styles/app.scss
  assets/styles/variables.scss
  config/packages/translation.yaml
  config/services.yaml
  migrations/Version20210622102650.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/includes/_navbar.html.twig
  templates/security/register.html.twig
Labels: Corrections done, Reviewed

#106 S04 us25 01 upload
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20210622142620.php
  src/Entity/Subscription.php
  symfony.lock
Labels: Reviewed

#103 US22 error 403
  assets/styles/error.scss
  src/Controller/ErrorController.php
  src/Controller/ProfileController.php
  templates/errors/error403.html.twig
  webpack.config.js
Labels: Reviewed

#104 Fix home page admin
  assets/styles/admin.scss
  templates/admin/index.html.twig
Labels: Reviewed

#113 Urgent fix upload for RV client
  migrations/Version20210622102650.php
  src/Entity/Subscription.php
Labels: Reviewed

#114 FIX flash message profile
  src/Controller/ProfileController.php
  symfony.lock
  templates/base.html.twig
  templates/includes/_flash_message.html.twig
Labels: Reviewed

#116 fixed words
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/security/register.html.twig
Labels: Reviewed

#101 S03 us21 twig rome extension
  .env
  src/Twig/ApiRomeExtension.php
  templates/profile/show.html.twig
Labels: Conflicts resolved, Reviewed

#119 Us04 form security
  src/Controller/HomeController.php
  src/Entity/VisitorTrip.php
  src/Service/Geocode.php
  templates/includes/_flash_message.html.twig
  templates/includes/_visitor_form.html.twig
Labels: Reviewed

#130 Us04 03 visitor trip on card
  assets/app.js
  assets/freeMap.js
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
  templates/includes/_visitor_form.html.twig
Labels: Reviewed

#111 S03 us19 mail de confirmation dinscription
  config/services.yaml
  src/Controller/SecurityController.php
  templates/mail/confirmationMail.html.twig
Labels: Corrections done, Reviewed

#102 S04 us23 interface gestion user
  assets/styles/admin.scss
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/admin/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
Labels: Corrections done, Reviewed

#129 S04 us27 01 entity fixtures testimony
  migrations/Version20210624085306.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Testimony.php
  src/Entity/User.php
  src/Repository/TestimonyRepository.php
Labels: Reviewed

#131 fix h card admin
  templates/admin/index.html.twig
Labels: Review requested, Waiting For Lucy

#133 Us04 fix markers
  assets/freeMap.js
Labels: Reviewed
