Repository WildCodeSchool/orleans-202103-php-project-jobpermut, pull requests merged in 2021-07, with the labels that each got.

#136 S04 us28 direction
  assets/freeMap.js
  config/services.yaml
  src/Controller/HomeController.php
  src/Controller/LeafletController.php
  src/Service/Direction.php
Labels: Corrections done, Reviewed

#125 US26 user settings
  assets/styles/setting.scss
  migrations/Version20210623154444.php
  src/Controller/ProfileController.php
  src/Controller/SecurityController.php
  src/Controller/SettingController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/ChangePassword.php
  src/Entity/User.php
  src/Form/ChangePasswordType.php
  src/Form/UserType.php
  templates/includes/_navbar.html.twig
  templates/setting/_form.html.twig
  templates/setting/change_password.html.twig
  templates/setting/edit.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#139 Us29 01 visitor trip summary
  assets/freeMap.js
  src/Controller/HomeController.php
  src/Controller/LeafletController.php
  src/Service/Direction.php
  src/Service/FormatDuration.php
  templates/home/index.html.twig
  templates/includes/_tripSummary.html.twig
Labels: Corrections done, Reviewed

#135 S05 us27 company entity
  migrations/Version20210701075724.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Entity/Subscription.php
  src/Entity/User.php
  src/Repository/CompanyRepository.php
Labels: Corrections done, Reviewed

#145 add entity
  migrations/Version20210705164032.php
  migrations/Version20210705202638.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/RomeFixtures.php
  src/Entity/RegisteredUser.php
  src/Entity/Rome.php
  src/Form/RegisteredUserType.php
  src/Repository/RomeRepository.php
  templates/profile/show.html.twig
Labels: Reviewed

#144 Us30 01 permutsearch view
  assets/styles/navbar.scss
  assets/styles/permutsearch.scss
  assets/styles/variables.scss
  src/Controller/PermutSearchController.php
  templates/includes/_navbar.html.twig
  templates/permutsearch/index.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#146 Connect ogr
  migrations/Version20210706073649.php
  src/Entity/Rome.php
  src/Entity/Subscription.php
  src/Service/ApiRome/ApiRomeAppellations.php
Labels: Reviewed

#149 Relation login registered
  assets/app.js
  src/Controller/SecurityController.php
  templates/home/index.html.twig
  templates/includes/_login.html.twig
Labels: Reviewed

#152 fix responsive
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/includes/_tripSummary.html.twig
  templates/includes/_visitor_form.html.twig
Labels: Reviewed

#147 S05 us27 admin testimony
  assets/styles/testimony.scss
  src/Controller/TestimonyController.php
  src/Entity/Testimony.php
  src/Entity/User.php
  templates/admin/index.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/show.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#157 fix sentence
  src/DataFixtures/SubscriptionFixtures.php
Labels: Reviewed

#155 Fix register
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/Security/AppAuthenticator.php
Labels: Corrections done, Reviewed

#156 Us31 02 permut search route and markers
  assets/permutMap.js
  assets/styles/permutsearch.scss
Labels: Corrections done, Reviewed

#159 S06 fix dev before master 20210707
  templates/includes/_tripSummary.html.twig
Labels: Reviewed

#158 S06 us33 realistic fixture
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#160 pr to master 20210707 before customer meeting
  assets/app.js
  assets/freeMap.js
  assets/permutMap.js
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/permutsearch.scss
  assets/styles/setting.scss
  assets/styles/testimony.scss
  assets/styles/variables.scss
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20210623154444.php
  migrations/Version20210701075724.php
  migrations/Version20210705164032.php
  migrations/Version20210705202638.php
  migrations/Version20210706073649.php
  src/Controller/HomeController.php
  src/Controller/LeafletController.php
  src/Controller/PermutSearchController.php
  src/Controller/ProfileController.php
  src/Controller/SecurityController.php
  src/Controller/SettingController.php
  src/Controller/TestimonyController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/RomeFixtures.php
  src/DataFixtures/SubscriptionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/ChangePassword.php
  src/Entity/Company.php
  src/Entity/RegisteredUser.php
  src/Entity/Rome.php
  src/Entity/Subscription.php
  src/Entity/Testimony.php
  src/Entity/User.php
  src/Form/ChangePasswordType.php
  src/Form/RegisteredUserType.php
  src/Form/UserType.php
  src/Repository/CompanyRepository.php
  src/Repository/RomeRepository.php
  src/Security/AppAuthenticator.php
  src/Service/ApiRome/ApiRomeAppellations.php
  src/Service/Direction.php
  src/Service/FormatDuration.php
  templates/admin/index.html.twig
  templates/home/index.html.twig
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_tripSummary.html.twig
  templates/includes/_visitor_form.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/setting/_form.html.twig
  templates/setting/change_password.html.twig
  templates/setting/edit.html.twig
  templates/testimony/_delete_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/show.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Reviewed

#148 S06 us25 02 admin crud company
  assets/styles/admin.scss
  assets/styles/adminCompany.scss
  src/Controller/CompanyController.php
  src/Form/CompanyType.php
  templates/admin/index.html.twig
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company/show.html.twig
  webpack.config.js
Labels: Corrections done, Please wait, Reviewed

#163 fix_nullable_is_visible
  migrations/Version20210707132337.php
  src/Entity/User.php
Labels: Reviewed

#166 fix master (dev->master)
  assets/styles/admin.scss
  assets/styles/adminCompany.scss
  migrations/Version20210707132337.php
  src/Controller/CompanyController.php
  src/Entity/User.php
  src/Form/CompanyType.php
  templates/admin/index.html.twig
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company/show.html.twig
  webpack.config.js
Labels: Reviewed

#167 Fix leaflet
  assets/app.js
  assets/permutMap.js
  src/Controller/PermutSearchController.php
  templates/permutsearch/index.html.twig
Labels: Reviewed

#165 S07 us34 real commentary
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#168 Us30 03 compare permut
  assets/permutMap.js
  assets/styles/permutsearch.scss
  src/Controller/PermutSearchController.php
  templates/permutsearch/_tripSummary1.html.twig
  templates/permutsearch/_tripSummary2.html.twig
  templates/permutsearch/index.html.twig
Labels: Reviewed

#171 Dev to Master
  assets/app.js
  assets/permutMap.js
  assets/styles/permutsearch.scss
  src/Controller/HomeController.php
  src/Controller/PermutSearchController.php
  templates/home/index.html.twig
  templates/permutsearch/_tripSummary1.html.twig
  templates/permutsearch/_tripSummary2.html.twig
  templates/permutsearch/index.html.twig
Labels: Reviewed

#173 Us35 01 matching
  assets/permutMap.js
  config/packages/security.yaml
  src/Controller/PermutSearchController.php
  src/DataFixtures/RegisteredUserFixtures.php
  src/Service/Direction.php
  templates/permutsearch/_tripSummary1.html.twig
  templates/permutsearch/_tripSummary2.html.twig
  templates/permutsearch/index.html.twig
Labels: Reviewed

#180 connect_btn
  assets/app.js
  templates/home/index.html.twig
  templates/includes/_tripSummary.html.twig
Labels: Reviewed

#178 Us35 like
  assets/like.js
  assets/styles/permutsearch.scss
  migrations/Version20210710140915.php
  src/Controller/LikeController.php
  src/Entity/Company.php
  src/Entity/User.php
  src/Entity/UserLike.php
  src/Repository/UserLikeRepository.php
  templates/permutsearch/index.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#182 Us35 fix
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Company.php
  src/Service/Direction.php
Labels: Reviewed

#183 cv repo
  public/uploads/.gitignore
  public/uploads/curriculums/.gitignore
  src/Entity/Company.php
Labels: Corrections done, Reviewed

#179 Add admin form
  src/Controller/AdminController.php
  src/Entity/Company.php
  src/Form/AdminType.php
  templates/admin/add.html.twig
  templates/admin/index.html.twig
  templates/company/index.html.twig
  templates/user/index.html.twig
Labels: Corrections done, Reviewed

#187 Match by like
  assets/like.js
  migrations/Version20210712140005.php
  src/Controller/LikeController.php
  src/Entity/MatchByLike.php
  src/Repository/MatchByLikeRepository.php
  templates/permutsearch/index.html.twig
Labels: Max priority, Reviewed

#188 Constraints Assert
  src/Entity/Subscription.php
Labels: Reviewed

#189 fix_error
  templates/permutsearch/index.html.twig
Labels: Reviewed

#190 Fix footer links
  templates/includes/_footer.html.twig
Labels: Reviewed

#192 add map to profile
  assets/profileMap.js
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  templates/profile/show.html.twig
  webpack.config.js
Labels: Reviewed

#193 inscription non accessible
  src/Controller/SecurityController.php
Labels: Reviewed

#196 add demo User to fixtures
  src/DataFixtures/RegisteredUserFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#195 dont show like on your profile
  templates/profile/show.html.twig
Labels: Reviewed

#197 fix like on profile
  assets/styles/profile.scss
  templates/profile/show.html.twig
Labels: Reviewed

#198 FIX error msg match
  templates/match/index.html.twig
Labels: Review requested

#199 Us36 showlike
  src/Controller/ProfileController.php
  src/Entity/User.php
  templates/includes/_navbar.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#200 avatar
  config/packages/vich_uploader.yaml
  migrations/Version20210713094326.php
  migrations/Version20210713094926.php
  public/uploads/avatars/klipartz-com-60ed68a8b773f369088632.png
  src/Entity/User.php
  src/Form/UserType.php
  templates/setting/_form.html.twig
Labels: Reviewed

#202 fix_serialize
  src/Entity/User.php
Labels: Reviewed

#203 Readme upgrade
  README.md
Labels: Corrections done, Lucy waiting for you, Max priority, Question, Review requested

#204 Add alert message in ShowLike
  templates/profile/showLike.html.twig
Labels: Reviewed

#206 FIX style
  assets/styles/footer.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/permutsearch.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#205 Fix random testimonies
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Conflicts resolved, Review requested

#207 Dev to master
  README.md
  assets/styles/footer.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/permutsearch.scss
  assets/styles/variables.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#209 Fix access to link
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#208 Fix avatar connect
  config/packages/security.yaml
  public/uploads/avatars/.gitignore
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#210 Fix Migration
  migrations/Version20210707132337.php
  migrations/Version20210710140915.php
  migrations/Version20210712131731.php
  migrations/Version20210712140005.php
  migrations/Version20210713094326.php
  migrations/Version20210713094926.php
  migrations/Version20210715100746.php
Labels: Reviewed

#214 FIX fixtures profile pic
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#212 del map if not reguser
  public/uploads/avatars/.gitignore
  public/uploads/avatars/klipartz-com-60ed68a8b773f369088632.png
  src/Controller/ProfileController.php
  templates/profile/show.html.twig
Labels: Reviewed

#215 fix_logo_premium
  templates/profile/show.html.twig
Labels: Reviewed

#211 Fix admin
  assets/styles/admin.scss
  templates/admin/index.html.twig
  templates/company/_form.html.twig
  templates/profile/show.html.twig
Labels: Conflicts resolved, Reviewed

#213 To fix migrations dev->master
  assets/styles/admin.scss
  config/packages/security.yaml
  migrations/Version20210707132337.php
  migrations/Version20210710140915.php
  migrations/Version20210712131731.php
  migrations/Version20210712140005.php
  migrations/Version20210713094326.php
  migrations/Version20210713094926.php
  migrations/Version20210715100746.php
  public/uploads/avatars/.gitignore
  public/uploads/avatars/klipartz-com-60ed68a8b773f369088632.png
  src/Controller/ProfileController.php
  src/DataFixtures/UserFixtures.php
  templates/admin/index.html.twig
  templates/company/_form.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar.html.twig
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#216 Sorry Mr Gadault
  README.md
Labels: Reviewed

#218 fix connect match
  templates/profile/showLike.html.twig
Labels: Reviewed

#219 modal display on responsive
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
Labels: Reviewed

#217 FIX avatar profile
  assets/styles/navbar.scss
  src/Twig/ImageSourceExtension.php
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Conflicts resolved, Reviewed

#220 fix avatar liked
  templates/profile/showLike.html.twig
Labels: Reviewed

#223 Fix profile
  assets/styles/permutsearch.scss
  assets/styles/profile.scss
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#221 Fix migration index
  migrations/Version20210715100746.php
Labels: Reviewed

#222 To test deploy after fixing migrations
  README.md
  assets/styles/navbar.scss
  assets/styles/permutsearch.scss
  assets/styles/profile.scss
  migrations/Version20210715100746.php
  src/Twig/ImageSourceExtension.php
  templates/home/index.html.twig
  templates/includes/_login.html.twig
  templates/includes/_navbar.html.twig
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Review requested

#224 fix for display the crown on the button
  assets/styles/profile.scss
Labels: Reviewed

#225 Fix ajax permutsearch
  assets/search.js
  assets/styles/permutsearch.scss
  src/Controller/PermutSearchController.php
  templates/permutsearch/index.html.twig
  templates/permutsearch/permut.html.twig
  webpack.config.js
Labels: Reviewed

#226 Translation route
  src/Controller/CompanyController.php
  src/Controller/TestimonyController.php
  src/Controller/UserController.php
Labels: Reviewed

#227 fix_cv
  src/DataFixtures/SubscriptionFixtures.php
Labels: Reviewed

#229 fix_color_client_btn
  templates/home/index.html.twig
Labels: Reviewed

#233 changed title
  templates/includes/_visitor_form.html.twig
Labels: Reviewed

#232 add testimony n admin part
  src/Controller/TestimonyController.php
  src/Form/TestimonyType.php
  templates/testimony/_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Reviewed

#231 text changed
  templates/home/index.html.twig
Labels: Reviewed

#228 Fix footer links
  templates/includes/_footer.html.twig
Labels: Reviewed

#234 correct error messages on register
  src/Controller/ProfileController.php
  src/Controller/SubscriptionController.php
  src/Entity/RegisteredUser.php
  src/Form/RegisteredUserType.php
Labels: Reviewed

#236 add text to trip summary and adapt style
  assets/styles/home.scss
  templates/includes/_tripSummary.html.twig
Labels: Reviewed

#238 fix_dot
  src/DataFixtures/SubscriptionFixtures.php
Labels: Reviewed

#237 Fix heart
  assets/styles/home.scss
  src/Controller/PermutSearchController.php
  templates/permutsearch/index.html.twig
Labels: Reviewed

#239 Fix flash direction
  src/Controller/LeafletController.php
  src/Controller/PermutSearchController.php
Labels: Reviewed

#241 Fix flash user data
  src/Controller/PermutSearchController.php
  src/Service/Direction.php
  templates/permutsearch/index.html.twig
Labels: Reviewed

#240 Dev To Master afeter first fix week
  assets/styles/home.scss
  src/Controller/LeafletController.php
  src/Controller/PermutSearchController.php
  src/DataFixtures/SubscriptionFixtures.php
  src/Service/Direction.php
  templates/includes/_tripSummary.html.twig
  templates/permutsearch/index.html.twig
Labels: Reviewed

#242 Fix profil edit
  templates/profile/show.html.twig
Labels: Reviewed

#244 Fix responsive permut card
  assets/styles/home.scss
  assets/styles/permutmatch.scss
  assets/styles/permutsearch.scss
  templates/match/index.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#243 errors
  composer.lock
  symfony.lock
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed

#246 Fix for Index for W3C Validator
  templates/includes/_login.html.twig
  templates/includes/_visitor_form.html.twig
Labels: Reviewed

#247 Fix W3C Validator on PermutSearch
  templates/permutsearch/_tripSummary1.html.twig
  templates/permutsearch/_tripSummary2.html.twig
Labels: Reviewed

#249 fix_heart
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#245 Fix comments
  src/Form/TestimonyType.php
  templates/testimony/_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Reviewed

#250 fix card
  assets/permutMap.js
  assets/styles/permutsearch.scss
  templates/permutsearch/index.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#252 Fix marker inversion
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
Labels: Reviewed

#253 add MAILER_FROM_ADDRESS
  .env
Labels: Reviewed

#254 rome_migration
  migrations/Version20210727151459.php
Labels: Reviewed

#251 Dev -> master
  .env
  assets/permutMap.js
  assets/styles/home.scss
  assets/styles/permutmatch.scss
  assets/styles/permutsearch.scss
  composer.lock
  migrations/Version20210727151459.php
  src/Form/TestimonyType.php
  symfony.lock
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/includes/_login.html.twig
  templates/includes/_visitor_form.html.twig
  templates/match/index.html.twig
  templates/permutsearch/_tripSummary1.html.twig
  templates/permutsearch/_tripSummary2.html.twig
  templates/permutsearch/index.html.twig
  templates/profile/show.html.twig
  templates/profile/showLike.html.twig
  templates/testimony/_form.html.twig
  templates/testimony/index.html.twig
  templates/testimony/new.html.twig
Labels: Reviewed

#255 fix_match
  src/Controller/MatchController.php
  src/Repository/MatchByLikeRepository.php
Labels: Reviewed

#256 fix_nav_match
  src/Controller/LikeController.php
Labels: Reviewed

#257 dev->master
  src/Controller/LikeController.php
  src/Controller/MatchController.php
  src/Repository/MatchByLikeRepository.php
Labels: Reviewed

#258 Fix inverted informations
  templates/profile/_form.html.twig
Labels: Reviewed

#259 Dev To Master
  templates/profile/_form.html.twig
Labels: Reviewed

#260 Fix Match vue
  templates/match/index.html.twig
Labels: Reviewed

#261 dev->master
  templates/match/index.html.twig
Labels: Reviewed
